name: jupyter-actions_v2
channels:
    - conda-forge
dependencies:  
  - jupyter
  - nbformat
  - nbconvert
  - papermill
  - numpy
  - pandas
  - folium
  - branca
  - matplotlib 
  - bokeh
  - holoviews<1.15
  - panel 
