name: Run-Notebooks

on:  
  push:
    branches:
      - master
  schedule:
  - cron: "0 0 */15 * *"
    
jobs:
  run-notebook:
    
    name: Run Notebook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2              
              
      - name: Set up GCS
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_MAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gsutil -m cp gs://pubsite_prod_7763943235860257566/stats/installs/* data/                
              
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: jupyter-actions
          environment-file: environment.yml
          python-version: 3.7
          mamba-version: "*"
          use-mamba: true
      
      - name: Execute all Notebooks and publish in docs
        shell: bash
        run: |
          conda init bash     
          source /home/runner/.bashrc     
          conda activate jupyter-actions
          papermill retrieveAppStats.ipynb output.ipynb
          jupyter nbconvert  output.ipynb --to html --output docs/index.html
      
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: update docs
          file_pattern: docs/*    
          
